# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.34
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _BehaviorAPI
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ModelTrait_None = _BehaviorAPI.ModelTrait_None
ModelTrait_Active = _BehaviorAPI.ModelTrait_Active
ModelTrait_BuiltinModel = _BehaviorAPI.ModelTrait_BuiltinModel
ModelTrait_ReplicaBuiltinModel = _BehaviorAPI.ModelTrait_ReplicaBuiltinModel
ModelTrait_ServerOnlyReplicaBuiltinModel = _BehaviorAPI.ModelTrait_ServerOnlyReplicaBuiltinModel
ModelTrait_ClientOnlyReplicaBuiltinModel = _BehaviorAPI.ModelTrait_ClientOnlyReplicaBuiltinModel
ModelTrait_ServerOnlyBuiltinModel = _BehaviorAPI.ModelTrait_ServerOnlyBuiltinModel
ModelTrait_ClientOnlyBuiltinModel = _BehaviorAPI.ModelTrait_ClientOnlyBuiltinModel
ModelTrait_ToolBuiltinModel = _BehaviorAPI.ModelTrait_ToolBuiltinModel
PropertyTrait_None = _BehaviorAPI.PropertyTrait_None
PropertyTrait_ReadOnly = _BehaviorAPI.PropertyTrait_ReadOnly
PropertyTrait_Private = _BehaviorAPI.PropertyTrait_Private
PropertyTrait_Persisted = _BehaviorAPI.PropertyTrait_Persisted
PropertyTrait_FromBuiltinModel = _BehaviorAPI.PropertyTrait_FromBuiltinModel
PropertyTrait_FromReplicaBuiltinModel = _BehaviorAPI.PropertyTrait_FromReplicaBuiltinModel
PropertyTrait_Mutable = _BehaviorAPI.PropertyTrait_Mutable
PropertyTrait_ServerOnly = _BehaviorAPI.PropertyTrait_ServerOnly
PropertyTrait_ClientOnly = _BehaviorAPI.PropertyTrait_ClientOnly
BehaviorTrait_None = _BehaviorAPI.BehaviorTrait_None
BehaviorTrait_Private = _BehaviorAPI.BehaviorTrait_Private
BehaviorTrait_ViewOnly = _BehaviorAPI.BehaviorTrait_ViewOnly
BehaviorTrait_NoBlock = _BehaviorAPI.BehaviorTrait_NoBlock
BehaviorTrait_Extends = _BehaviorAPI.BehaviorTrait_Extends
BehaviorTrait_Immediate = _BehaviorAPI.BehaviorTrait_Immediate
BehaviorTrait_InWorldOnly = _BehaviorAPI.BehaviorTrait_InWorldOnly
BehaviorTrait_ServerExecOnly = _BehaviorAPI.BehaviorTrait_ServerExecOnly
BehaviorTrait_ClientExecOnly = _BehaviorAPI.BehaviorTrait_ClientExecOnly
BehaviorTrait_RemotelyVisible = _BehaviorAPI.BehaviorTrait_RemotelyVisible
BehaviorTrait_Init = _BehaviorAPI.BehaviorTrait_Init
BehaviorType_Invalid = _BehaviorAPI.BehaviorType_Invalid
BehaviorType_C = _BehaviorAPI.BehaviorType_C
BehaviorType_Cpp = _BehaviorAPI.BehaviorType_Cpp
BehaviorType_Builtin = _BehaviorAPI.BehaviorType_Builtin
BehaviorType_Remote = _BehaviorAPI.BehaviorType_Remote
BehaviorType_Virtual = _BehaviorAPI.BehaviorType_Virtual
BehaviorType_Lua = _BehaviorAPI.BehaviorType_Lua
BehaviorType_Python = _BehaviorAPI.BehaviorType_Python
BehaviorType_Abstract = _BehaviorAPI.BehaviorType_Abstract
GetServiceManagerTime = _BehaviorAPI.GetServiceManagerTime
GetGameTime = _BehaviorAPI.GetGameTime
CreateCategory = _BehaviorAPI.CreateCategory
CreateApplicationCategory = _BehaviorAPI.CreateApplicationCategory
GetServicePublicCategory = _BehaviorAPI.GetServicePublicCategory
GetServiceProcessUniqueCategory = _BehaviorAPI.GetServiceProcessUniqueCategory
GetGloballyUniqueCategory = _BehaviorAPI.GetGloballyUniqueCategory
GetEnumValue = _BehaviorAPI.GetEnumValue
DoesModelExist = _BehaviorAPI.DoesModelExist
SendEvent = _BehaviorAPI.SendEvent
SendReply = _BehaviorAPI.SendReply
CallBehavior = _BehaviorAPI.CallBehavior
SendStream = _BehaviorAPI.SendStream
SendStreamLocal = _BehaviorAPI.SendStreamLocal
FlexLogMessage = _BehaviorAPI.FlexLogMessage
FlexLogError = _BehaviorAPI.FlexLogError
LogMessage = _BehaviorAPI.LogMessage
LogError = _BehaviorAPI.LogError
LogMessageLua = _BehaviorAPI.LogMessageLua
LogErrorLua = _BehaviorAPI.LogErrorLua
OutputDebugMessage = _BehaviorAPI.OutputDebugMessage
GetPropertyCount = _BehaviorAPI.GetPropertyCount
AddUpdateNotificationByEntity = _BehaviorAPI.AddUpdateNotificationByEntity
AddUpdateNotificationByModel = _BehaviorAPI.AddUpdateNotificationByModel
GetExecutingEntityId = _BehaviorAPI.GetExecutingEntityId
GetCurrentEventID = _BehaviorAPI.GetCurrentEventID
GetReturnEntityId = _BehaviorAPI.GetReturnEntityId
ec_Yes = _BehaviorAPI.ec_Yes
ec_No = _BehaviorAPI.ec_No
ec_EntityNotFound = _BehaviorAPI.ec_EntityNotFound
IsKindOf = _BehaviorAPI.IsKindOf
HasMixin = _BehaviorAPI.HasMixin
HasBehavior = _BehaviorAPI.HasBehavior
HasProperty = _BehaviorAPI.HasProperty
HasPropertyKey = _BehaviorAPI.HasPropertyKey
FindMixins = _BehaviorAPI.FindMixins
FindMatchingMixins = _BehaviorAPI.FindMatchingMixins
FindBehaviors = _BehaviorAPI.FindBehaviors
FindMatchingBehaviors = _BehaviorAPI.FindMatchingBehaviors
FindProperties = _BehaviorAPI.FindProperties
FindMatchingProperties = _BehaviorAPI.FindMatchingProperties
FindPropertyKeys = _BehaviorAPI.FindPropertyKeys
GetNextPropertyKey = _BehaviorAPI.GetNextPropertyKey
GetBehaviorSource = _BehaviorAPI.GetBehaviorSource
GetPropertySource = _BehaviorAPI.GetPropertySource
ResetProperty = _BehaviorAPI.ResetProperty
RemovePropertyValue = _BehaviorAPI.RemovePropertyValue
FindAllEntities = _BehaviorAPI.FindAllEntities
FindEntitiesByModel = _BehaviorAPI.FindEntitiesByModel
FindEntitiesByBaseModel = _BehaviorAPI.FindEntitiesByBaseModel
FindEntityByDataID = _BehaviorAPI.FindEntityByDataID
FindAllBehaviors = _BehaviorAPI.FindAllBehaviors
SubscribeToCategory = _BehaviorAPI.SubscribeToCategory
UnsubscribeToCategory = _BehaviorAPI.UnsubscribeToCategory
CreateEntity = _BehaviorAPI.CreateEntity
SpawnEntity = _BehaviorAPI.SpawnEntity
DestroyEntity = _BehaviorAPI.DestroyEntity
EntityEnterWorld = _BehaviorAPI.EntityEnterWorld
EntityExitWorld = _BehaviorAPI.EntityExitWorld
IsEntityInWorld = _BehaviorAPI.IsEntityInWorld
IncrementProperty = _BehaviorAPI.IncrementProperty
DecrementProperty = _BehaviorAPI.DecrementProperty
SwapProperty = _BehaviorAPI.SwapProperty
GetConfigValue = _BehaviorAPI.GetConfigValue
GetPlatformName = _BehaviorAPI.GetPlatformName
GetBuildConfiguration = _BehaviorAPI.GetBuildConfiguration
EntitySetEnterWorld = _BehaviorAPI.EntitySetEnterWorld
EntitySetExitWorld = _BehaviorAPI.EntitySetExitWorld

GetProperty = _BehaviorAPI.GetProperty
GetDefaultProperty = _BehaviorAPI.GetDefaultProperty
SetProperty = _BehaviorAPI.SetProperty
SendAndWaitForReply = _BehaviorAPI.SendAndWaitForReply
Sleep = _BehaviorAPI.Sleep
cvar = _BehaviorAPI.cvar
kFlatModelID_INVALID = cvar.kFlatModelID_INVALID
kPropertyID_INVALID = cvar.kPropertyID_INVALID
kBehaviorID_INVALID = cvar.kBehaviorID_INVALID
GetServicePrivateCategory = _BehaviorAPI.GetServicePrivateCategory
GetModelName = _BehaviorAPI.GetModelName
LoadBlockFile = _BehaviorAPI.LoadBlockFile
UnloadBlockFile = _BehaviorAPI.UnloadBlockFile

