// EMERGENT GAME TECHNOLOGIES PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Emergent Game Technologies and may not
// be copied or disclosed except in accordance with the terms of that
// agreement.
//
//      Copyright (c) 1996-2009 Emergent Game Technologies.
//      All Rights Reserved.
//
// Emergent Game Technologies, Calabasas, CA 91302
// http://www.emergent.net

#pragma once
#ifndef NIANIMATION_H
#define NIANIMATION_H

// DLL support
#include "NiAnimationLibType.h"

#include "NiActorManager.h"
#include "NiAlphaController.h"
#include "NiAnimationConstants.h"
#include "NiAnimationKey.h"
#include "NiAnimationKeyMacros.h"
#include "NiAnimationMetrics.h"
#include "NiBezFloatKey.h"
#include "NiBezPosKey.h"
#include "NiBezRotKey.h"
#include "NiBlendBoolInterpolator.h"
#include "NiBlendColorInterpolator.h"
#include "NiBlendFloatInterpolator.h"
#include "NiBlendInterpolator.h"
#include "NiBlendPoint3Interpolator.h"
#include "NiBlendQuaternionInterpolator.h"
#include "NiBlendTransformInterpolator.h"
#include "NiBoneLODController.h"
#include "NiBoolData.h"
#include "NiBoolEvaluator.h"
#include "NiBoolInterpController.h"
#include "NiBoolInterpolator.h"
#include "NiBoolKey.h"
#include "NiBoolTimelineEvaluator.h"
#include "NiBoolTimelineInterpolator.h"
#include "NiBSplineBasis.h"
#include "NiBSplineBasisData.h"
#include "NiBSplineColorEvaluator.h"
#include "NiBSplineColorInterpolator.h"
#include "NiBSplineCompColorEvaluator.h"
#include "NiBSplineCompColorInterpolator.h"
#include "NiBSplineCompFloatEvaluator.h"
#include "NiBSplineCompFloatInterpolator.h"
#include "NiBSplineCompPoint3Evaluator.h"
#include "NiBSplineCompPoint3Interpolator.h"
#include "NiBSplineCompTransformEvaluator.h"
#include "NiBSplineCompTransformInterpolator.h"
#include "NiBSplineData.h"
#include "NiBSplineEvaluator.h"
#include "NiBSplineFit.h"
#include "NiBSplineFloatEvaluator.h"
#include "NiBSplineFloatInterpolator.h"
#include "NiBSplineInterpolator.h"
#include "NiBSplinePoint3Evaluator.h"
#include "NiBSplinePoint3Interpolator.h"
#include "NiBSplineTransformEvaluator.h"
#include "NiBSplineTransformInterpolator.h"
#include "NiColorData.h"
#include "NiColorEvaluator.h"
#include "NiColorExtraDataController.h"
#include "NiColorInterpController.h"
#include "NiColorInterpolator.h"
#include "NiColorKey.h"
#include "NiConstBoolEvaluator.h"
#include "NiConstColorEvaluator.h"
#include "NiConstFloatEvaluator.h"
#include "NiConstPoint3Evaluator.h"
#include "NiConstQuaternionEvaluator.h"
#include "NiConstTransformEvaluator.h"
#include "NiControllerManager.h"
#include "NiControllerSequence.h"
#include "NiEulerRotKey.h"
#include "NiEvaluator.h"
#include "NiEvaluatorSPData.h"
#include "NiExtraDataController.h"
#include "NiFlipController.h"
#include "NiFloatData.h"
#include "NiFloatEvaluator.h"
#include "NiFloatExtraDataController.h"
#include "NiFloatInterpController.h"
#include "NiFloatInterpolator.h"
#include "NiFloatKey.h"
#include "NiFloatsExtraDataController.h"
#include "NiFloatsExtraDataPoint3Controller.h"
#include "NiGeomMorpherController.h"
#include "NiInterpController.h"
#include "NiInterpolator.h"
#include "NiInterpolatorConverter.h"
#include "NiInterpScalar.h"
#include "NiKeyBasedEvaluator.h"
#include "NiKeyBasedInterpolator.h"
#include "NiKFMTool.h"
#include "NiLightColorController.h"
#include "NiLightDimmerController.h"
#include "NiLinColorKey.h"
#include "NiLinFloatKey.h"
#include "NiLinPosKey.h"
#include "NiLinRotKey.h"
#include "NiLookAtEvaluator.h"
#include "NiLookAtInterpolator.h"
#include "NiMaterialColorController.h"
#include "NiMorphData.h"
#include "NiMorphWeightsController.h"
#include "NiMultiTargetPoseHandler.h"
#include "NiMultiTargetTransformController.h"
#include "NiPathEvaluator.h"
#include "NiPathInterpolator.h"
#include "NiPoint3Evaluator.h"
#include "NiPoint3InterpController.h"
#include "NiPoint3Interpolator.h"
#include "NiPosData.h"
#include "NiPoseBinding.h"
#include "NiPoseBuffer.h"
#include "NiPoseBufferHandle.h"
#include "NiPosKey.h"
#include "NiPrimeNumber.h"
#include "NiQuaternionInterpController.h"
#include "NiQuaternionEvaluator.h"
#include "NiQuaternionInterpolator.h"
#include "NiQuatTransform.h"
#include "NiRotData.h"
#include "NiRotKey.h"
#include "NiScratchPad.h"
#include "NiScratchPadBlock.h"
#include "NiSequenceData.h"
#include "NiSingleInterpController.h"
#include "NiSkinningLODController.h"
#include "NiSpline.h"
#include "NiStepBoolKey.h"
#include "NiStepColorKey.h"
#include "NiStepFloatKey.h"
#include "NiStepPosKey.h"
#include "NiStepRotKey.h"
#include "NiStringPalette.h"
#include "NiTCBFloatKey.h"
#include "NiTCBPosKey.h"
#include "NiTCBRotKey.h"
#include "NiTextKey.h"
#include "NiTextKeyExtraData.h"
#include "NiTextKeyMatch.h"
#include "NiTextureTransformController.h"
#include "NiTransformController.h"
#include "NiTransformData.h"
#include "NiTransformEvaluator.h"
#include "NiTransformInterpolator.h"
#include "NiVisController.h"

#include "NiGeomMorpherConverter.h"
#include "NiOldAnimationConverter.h"

#include "NiAnimationSDM.h"
static NiAnimationSDM NiAnimationSDMObject;

#endif  // #ifndef NIANIMATION_H
